services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot-data:/app/bot-data
      - ./keywords.yml:/app/keywords.yml
    command:
      - "--keywords-file"
      - "/app/keywords.yml"
      - "--watch-file"
      # - "--reactions-collector-load-history"
    ports:
      - 0.0.0.0:9669:9669
